### ISSUE TITLE
Script settings from bash

### ISSUE THREAD

**Issue by NeoMatrixJR** [pardus/gnome-shell-extension-arc-menu#5]
I've been working to automate my setup. I've been getting most of my gnome config set via `gsettings set org.gnome.shell.extensions.whatever setting value` When I try that with arcmenu I just get "No such schema "org.gnome.shell.extensions.arcmenu"

Is there any way to config this from a script/CLI? I haven't been able to find anything so far.

**Comment by osmancoskun** [comment]
I guess you are trying to set some values for arcmenu for your needs. 
You can see some extensions got key values in dconf editor but not available to set / get with gsettings. 
Which is called [relocatable schemas](https://blog.gtk.org/2017/05/01/first-steps-with-gsettings/)

> A relocatable schema is what you need when you need multiple instances of the same configuration, stored separately. A typical example for this is accounts: your application allows to create more than one, and each of them has the same kind of configuration information associated with it.

You can use dconf for that.
Usage is almost simple as gsettings.
Lets assume you have a 
`schema = org.gnome.shell.extensions.myextension`
`key = mykey`
and `value = myvalue`
To set this you use gsettings as
```sh
gsettings set org.gnome.shell.extensions.myextension mykey myvalue
```
With dconf its almost same but you need to make some changes like the following
```sh
dconf write /org/gnome/shell/extensions/myextension/mykey myvalue
```
if you these commands doesnt work and there is some custom things, you can watch dconf changes with
```sh
dconf watch /
```

**Comment by NeoMatrixJR** [comment]
Thank you!  Exactly what I needed!
